# Generated by Django 4.1.3 on 2022-12-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=5, max_length=25),
            preserve_default=False,
        ),
    ]
